# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87439fd13bc66baf56e06ef2b42061dc11584612580a254e0bf7c684bfae43c3ef7256e5dc5a558c1d7674e47eaa3e078ddba82f21dff98d9f78204d0ef08a3a

test:
  secret_key_base: 3f15992bd7e5ee70d64f87c3f499bd3031e51687136cd81ff1784b44c150ef03021940cb3b0f1334504aa67b5efa52bda5b2953c35642c810639db836115f9c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
